jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./check/test

name: Workflow

on:
  schedule:
    - cron: "30 */6 * * *"
